name: CLIENT_PRODUCTION

on:
  workflow_dispatch:

jobs:
  build-img:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r23c
      - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./app/src/main/jni/Android.mk NDK_APPLICATION_MK=./app/src/main/jni/Application.mk
      
