name: CLIENT_PRODUCTION

on:
  workflow_dispatch:

jobs:
  build-img:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25b
      - run: ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk NDK_APPLICATION_MK=./Application.mk
      
